# Input & Mouse Behavior
input {
    follow_mouse = 1
    mouse_refocus = true
}

misc {
    focus_on_activate = true
    mouse_move_enables_dpms = true
    animate_manual_resizes = true
}

# General Layout
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = rgba(0078d4ff) rgba(00b7c3ff) 45deg
}

# Decoration
decoration {
    rounding = 10
    blur {
        enabled = true
        size = 8
        passes = 2
        vibrancy = 0.2
    }
    shadow {
        enabled = true
        range = 24
        render_power = 3
        color = rgba(00000066)
    }
}

# Animations
animations {
    enabled = yes

    bezier = fluent, 0.1, 0.9, 0.2, 1.0
    bezier = fluentExit, 0.2, 1.0, 0.1, 1.0

    animation = windows, 1, 5, fluent
    animation = windowsIn, 1, 5, fluent, popin 90%
    animation = windowsOut, 1, 3, fluentExit, popin 90%
    animation = workspaces, 1, 4, fluent, slide
    animation = specialWorkspace, 1, 4, fluent, slidevert
    animation = layers, 1, 4, fluent, fade
}


# File Explorer / File Manager window rules
windowrulev2 = float, class:^(com.thisisgm.flea|flea|org.gnome.Nautilus|thunar|org.kde.dolphin|nemo|pcmanfm)$
windowrulev2 = size 1080 680, class:^(com.thisisgm.flea|flea|org.gnome.Nautilus|thunar|org.kde.dolphin|nemo|pcmanfm)$
windowrulev2 = center, class:^(com.thisisgm.flea|flea|org.gnome.Nautilus|thunar|org.kde.dolphin|nemo|pcmanfm)$
windowrulev2 = rounding 10, class:^(com.thisisgm.flea|flea|org.gnome.Nautilus|thunar|org.kde.dolphin|nemo|pcmanfm)$

# Windows 11 Keybindings
bindrd = , SUPER_L, exec, omarchy-undercover-launcher
bind = SUPER, space, exec, omarchy-undercover-launcher
bind = SUPER, e, exec, omarchy-undercover-filemanager
bind = SUPER, tab, exec, rofi -show window -theme ~/.config/rofi/windows11.rasi
bind = SUPER, a, exec, omarchy-win11-actioncenter
bind = SUPER, n, exec, omarchy-win11-notifications
bind = SUPER ALT, w, exec, omarchy-win11-widgets
bind = SUPER, i, exec, uwsm-app -- omarchy-undercover-settings
bind = SUPER, d, exec, omarchy-undercover-show-desktop
bind = SUPER, z, exec, omarchy-undercover-snap menu
bind = SUPER SHIFT, s, exec, omarchy capture screenshot region copy
bind = SUPER, v, exec, omarchy-launch-walker -m clipboard
bind = ALT, F4, killactive
bind = SUPER, l, exec, hyprlock || swaylock || loginctl lock-session
bind = SUPER, left, exec, omarchy-undercover-snap left
bind = SUPER, right, exec, omarchy-undercover-snap right
bind = SUPER, up, exec, omarchy-undercover-snap up
bind = SUPER, down, exec, omarchy-undercover-snap down


